import {demoMode} from './demo';
const issuer=(import.meta.env.VITE_OAUTH_ISSUER||'http://localhost:9000').replace(/\/$/,'');
const clientId=import.meta.env.VITE_OAUTH_CLIENT_ID||'technotes-web';
const scope=import.meta.env.VITE_OAUTH_SCOPE||'openid profile notes.read notes.write notes.review taxonomy.write profile.read';
const callback=()=>`${window.location.origin}/auth/callback`;
const b64url=(bytes)=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const random=()=>b64url(crypto.getRandomValues(new Uint8Array(32)));
const challenge=async verifier=>b64url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));
const key='technotes.auth';const pending='technotes.pkce';
export function session(){if(demoMode)return sessionStorage.getItem('technotes.demo.login')?{access_token:'demo-only',expiresAt:Date.now()+3600000}:null;try{const x=JSON.parse(sessionStorage.getItem(key));if(x?.access_token && Date.now()<x.expiresAt-30000)return x}catch{}return null}
export function clearSession(){sessionStorage.removeItem('technotes.demo.login');sessionStorage.removeItem(key);sessionStorage.removeItem(pending)}
export async function login(){if(demoMode){sessionStorage.setItem('technotes.demo.login','yes');location.assign('/admin');return}const verifier=random(),state=random(),nonce=random();sessionStorage.setItem(pending,JSON.stringify({verifier,state,nonce,returnTo:location.pathname==='/'?'/':location.pathname}));const u=new URL(`${issuer}/oauth2/authorize`);Object.entries({response_type:'code',client_id:clientId,redirect_uri:callback(),scope,state,nonce,code_challenge:await challenge(verifier),code_challenge_method:'S256'}).forEach(([k,v])=>u.searchParams.set(k,v));location.assign(u.href)}
export async function finishLogin(){const q=new URLSearchParams(location.search),p=JSON.parse(sessionStorage.getItem(pending)||'null');if(q.get('error'))throw new Error(q.get('error_description')||q.get('error'));if(!p||!q.get('code')||q.get('state')!==p.state)throw new Error('Login state did not match. Please sign in again.');const body=new URLSearchParams({grant_type:'authorization_code',client_id:clientId,code:q.get('code'),redirect_uri:callback(),code_verifier:p.verifier});const r=await fetch(`${issuer}/oauth2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await r.json();if(!r.ok||!data.access_token)throw new Error(data.error_description||data.error||'Token exchange failed');const value={access_token:data.access_token,expiresAt:Date.now()+(Number(data.expires_in)||600)*1000};sessionStorage.setItem(key,JSON.stringify(value));sessionStorage.removeItem(pending);return p.returnTo?.startsWith('/')&&!p.returnTo.startsWith('//')?p.returnTo:'/admin'}
